config/routes.rb
Tetsuzine::Application.routes.draw do
  devise_for :users
  scope :users do
    match 'books/new', :to => 'books#search', :via => :post
    match 'books/new', :to => 'books#new_result', :via => :post, :as => 'resister'
    resources :books
  end
  resources :users
  resources :readings
  resources :authors
  resources :publishers
  resources :books

  root 'books#index'

  

end

app/models/reading.rb
class Reading < ActiveRecord::Base
  belongs_to :book
end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController
  before_action :set_reading, only: [:show, :edit, :update, :destroy]

  # GET /readings
  # GET /readings.json
  def index
    @readings = Reading.all
  end

  # GET /readings/1
  # GET /readings/1.json
  def show
  end

  # GET /readings/new
  def new
    @reading = Reading.new
  end

  # GET /readings/1/edit
  def edit
  end

  # POST /readings
  # POST /readings.json
  def create
    @reading = Reading.new(reading_params)

    respond_to do |format|
      if @reading.save
        format.html { redirect_to @reading, notice: 'Reading was successfully created.' }
        format.json { render action: 'show', status: :created, location: @reading }
      else
        format.html { render action: 'new' }
        format.json { render json: @reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /readings/1
  # PATCH/PUT /readings/1.json
  def update
    respond_to do |format|
      if @reading.update(reading_params)
        format.html { redirect_to @reading, notice: 'Reading was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /readings/1
  # DELETE /readings/1.json
  def destroy
    @reading.destroy
    respond_to do |format|
      format.html { redirect_to readings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reading
      @reading = Reading.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reading_params
      params.require(:reading).permit(:book_id, :started_on, :finished_on, :comment)
    end
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/views/readings/_form.html.slim
= form_for @reading do |f|
  - if @reading.errors.any?
    #error_explanation
      h2 = "#{pluralize(@reading.errors.count, "error")} prohibited this reading from being saved:"
      ul
        - @reading.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :book
    = f.text_field :book
  .field
    = f.label :started_on
    = f.date_select :started_on
  .field
    = f.label :finished_on
    = f.date_select :finished_on
  .field
    = f.label :comment
    = f.text_area :comment
  .actions = f.submit 'Save'

app/views/readings/edit.html.slim
h1 Editing reading

== render 'form'

= link_to 'Show', @reading
'|
= link_to 'Back', readings_path

app/views/readings/index.html.slim
h1 Listing readings

table
  tr
    th Book
    th Started on
    th Finished on
    th Comment
    th
    th
    th

  - @readings.each do |reading|
    tr
      td = reading.book
      td = reading.started_on
      td = reading.finished_on
      td = reading.comment
      td = link_to 'Show', reading
      td = link_to 'Edit', edit_reading_path(reading)
      td = link_to 'Destroy', reading, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Reading', new_reading_path

app/views/readings/new.html.slim
h1 New reading

== render 'form'

= link_to 'Back', readings_path

app/views/readings/show.html.slim
p#notice = notice

p
  strong Book:
  = @reading.book
p
  strong Started on:
  = @reading.started_on
p
  strong Finished on:
  = @reading.finished_on
p
  strong Comment:
  = @reading.comment

= link_to 'Edit', edit_reading_path(@reading)
'|
= link_to 'Back', readings_path