config/routes.rb
Tetsuzine::Application.routes.draw do
  devise_for :users
  scope :users do
    match 'books/new', :to => 'books#search', :via => :post
    match 'books/new', :to => 'books#new_result', :via => :post, :as => 'resister'
    resources :books
  end
  resources :users
  resources :readings
  resources :authors
  resources :publishers
  resources :books

  root 'books#index'

  

end

app/models/author.rb
class Author < ActiveRecord::Base
  belongs_to :book
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render action: 'show', status: :created, location: @author }
      else
        format.html { render action: 'new' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:book_id, :name)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.slim
= form_for @author do |f|
  - if @author.errors.any?
    #error_explanation
      h2 = "#{pluralize(@author.errors.count, "error")} prohibited this author from being saved:"
      ul
        - @author.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :book
    = f.text_field :book
  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit 'Save'

app/views/authors/edit.html.slim
h1 Editing author

== render 'form'

= link_to 'Show', @author
'|
= link_to 'Back', authors_path

app/views/authors/index.html.slim
h1 Listing authors

table
  tr
    th Book
    th Name
    th
    th
    th

  - @authors.each do |author|
    tr
      td = author.book
      td = author.name
      td = link_to 'Show', author
      td = link_to 'Edit', edit_author_path(author)
      td = link_to 'Destroy', author, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Author', new_author_path

app/views/authors/new.html.slim
h1 New author

== render 'form'

= link_to 'Back', authors_path

app/views/authors/show.html.slim
p#notice = notice

p
  strong Book:
  = @author.book
p
  strong Name:
  = @author.name

= link_to 'Edit', edit_author_path(@author)
'|
= link_to 'Back', authors_path