config/routes.rb
Tetsuzine::Application.routes.draw do
  devise_for :users
  scope :users do
    match 'books/new', :to => 'books#search', :via => :post
    match 'books/new', :to => 'books#new_result', :via => :post, :as => 'resister'
    resources :books
  end
  resources :users
  resources :readings
  resources :authors
  resources :publishers
  resources :books

  root 'books#index'

  

end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  belongs_to :book
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  before_action :set_publisher, only: [:show, :edit, :update, :destroy]

  # GET /publishers
  # GET /publishers.json
  def index
    @publishers = Publisher.all
  end

  # GET /publishers/1
  # GET /publishers/1.json
  def show
  end

  # GET /publishers/new
  def new
    @publisher = Publisher.new
  end

  # GET /publishers/1/edit
  def edit
  end

  # POST /publishers
  # POST /publishers.json
  def create
    @publisher = Publisher.new(publisher_params)

    respond_to do |format|
      if @publisher.save
        format.html { redirect_to @publisher, notice: 'Publisher was successfully created.' }
        format.json { render action: 'show', status: :created, location: @publisher }
      else
        format.html { render action: 'new' }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publishers/1
  # PATCH/PUT /publishers/1.json
  def update
    respond_to do |format|
      if @publisher.update(publisher_params)
        format.html { redirect_to @publisher, notice: 'Publisher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publishers/1
  # DELETE /publishers/1.json
  def destroy
    @publisher.destroy
    respond_to do |format|
      format.html { redirect_to publishers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publisher
      @publisher = Publisher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publisher_params
      params.require(:publisher).permit(:book_id, :name)
    end
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/publishers/_form.html.slim
= form_for @publisher do |f|
  - if @publisher.errors.any?
    #error_explanation
      h2 = "#{pluralize(@publisher.errors.count, "error")} prohibited this publisher from being saved:"
      ul
        - @publisher.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :book
    = f.text_field :book
  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit 'Save'

app/views/publishers/edit.html.slim
h1 Editing publisher

== render 'form'

= link_to 'Show', @publisher
'|
= link_to 'Back', publishers_path

app/views/publishers/index.html.slim
h1 Listing publishers

table
  tr
    th Book
    th Name
    th
    th
    th

  - @publishers.each do |publisher|
    tr
      td = publisher.book
      td = publisher.name
      td = link_to 'Show', publisher
      td = link_to 'Edit', edit_publisher_path(publisher)
      td = link_to 'Destroy', publisher, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Publisher', new_publisher_path

app/views/publishers/new.html.slim
h1 New publisher

== render 'form'

= link_to 'Back', publishers_path

app/views/publishers/show.html.slim
p#notice = notice

p
  strong Book:
  = @publisher.book
p
  strong Name:
  = @publisher.name

= link_to 'Edit', edit_publisher_path(@publisher)
'|
= link_to 'Back', publishers_path